### ISSUE TITLE
Chapter-1 validation issue

### ISSUE THREAD

**Issue by lopezi** [learn-ocean/ocean-academy#30]
Chapter-1 validates positively without any selected option.
As a user I should be able to validate chapter #1 only after selecting one or more options?

<img width="617" alt="Screen Shot 2020-12-04 at 17 45 04" src="https://user-images.githubusercontent.com/388476/101196784-178c6c00-3659-11eb-839c-bec6ded9626e.png">

**Comment by oceanByte** [comment]
@MeMent0L might have a strong opinion here. 

This was considered a feature since we didn't want to enforce an answer. But it was reported as a bug by different users already. I think we should change the question with a completely new one which enforces an answer.

The file can be found here: 
`ocean-academy/src/frontend/src/pages/Chapters/Chapter1/questions.ts`

**Comment by MeMent0L** [comment]
> 
> 
> @MeMent0L might have a strong opinion here.
> 
> This was considered a feature since we didn't want to enforce an answer. But it was reported as a bug by different users already. I think we should change the question with a completely new one which enforces an answer.
> 
> The file can be found here:
> `ocean-academy/src/frontend/src/pages/Chapters/Chapter1/questions.ts`

Moved to /ocean-academy/tree/main/src/frontend/src/pages/Courses/ocean101/Chapters/Chapter1/questions.ts

**Comment by oceanByte** [comment]
Merged with https://github.com/learn-ocean/ocean-academy/pull/52.
