### ISSUE TITLE
Change Front Page

### ISSUE THREAD

**Issue by SarahKay99** [learn-ocean/ocean-academy#43]
[EDITED] We need to change our front page to look like this: ![Wireframe](https://trello-attachments.s3.amazonaws.com/5fc0ea4a548fce14b21aa325/1175x660/69e1a4951f14369c7497a06e24631447/image.png)

I suggest these tasks:

- [ ] Refactor site data to allow for multiple courses & store course data. 
- [ ] Create CourseBox element, to contain the course summaries + links.
- [ ] Hook up course data & links with CourseBox element.
- [ ] Simplify summary text & add Manta Ray or Shrimp icon.

Figma Links: 
- https://www.figma.com/file/If6wwgh7KLKNYMOJzPXx31/OceanAcademy.io (wireframes)
- https://www.figma.com/file/UXKjbq8bNSGWHkHh2UPIsM/Assets (ocean assets, including Manta Ray)
- https://github.com/SarahKay99/Rockpool (Rockpool, access Mantis Shrimp from here)

@oceanByte What do you think?

**Comment by oceanByte** [comment]
> I suggest these tasks:
> 
> * [ ]  Refactor site data to allow for multiple courses & store course data. Reward: ?
> * [ ]  Create CourseBox element, to contain the course summaries + links. Reward: ?
> * [ ]  Hook up course data & links with CourseBox element. Reward: ?
> * [ ]  Simplify summary text & add Manta Ray or Shrimp icon. Reward: ?
> 
> Overall Reward Allocation: ?
> 
> @oceanByte What do you think?

Any rewards (if applicable) are discussed on Trello. GitHub should focus on the task description. Remove the reward tags.

Please provide the Figma link to the design in the comments in case someone else wants to contribute as well. Images should be used to express a point but they are a bad reference while implementing the given design. 

I also assigned you to the task so that everyone knows someone is working on it.

**Comment by oceanByte** [comment]
Merged with https://github.com/learn-ocean/ocean-academy/pull/57
